[package]
name = "listening-stats"
version = "0.1.0"
edition = "2024"
authors = ["David Duran <dadch1404@gmail.com>"]
license = "MIT"

[dependencies]
anyhow = "1.0.100"
dotenv = "0.15.0"
reqwest = { version = "0.12.24", features = ["json"]}
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
unicode-width = "0.2.2"
